"""
Learning Brain Models

Author : Super Cat
Project: Trading Market AI

All data models used by the Learning Brain.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional
import uuid


# ==========================================================
# Prediction Record
# ==========================================================

@dataclass
class PredictionRecord:
    """
    Stores every prediction generated by the AI.
    """

    prediction_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    timestamp: datetime = field(default_factory=datetime.now)

    symbol: str = "NIFTY"

    timeframe: str = "3m"

    current_price: float = 0.0

    decision: str = "HOLD"

    confidence: float = 0.0

    # Individual brain outputs
    price_action_signal: str = "NEUTRAL"

    live_market_signal: str = "NEUTRAL"

    options_signal: str = "NEUTRAL"

    global_market_signal: str = "NEUTRAL"

    # Market Information

    support: float = 0.0

    resistance: float = 0.0

    atr: float = 0.0

    vix: float = 0.0

    trend: str = "SIDEWAYS"

    reason: str = ""

    extra: dict = field(default_factory=dict)


# ==========================================================
# Trade Outcome
# ==========================================================

@dataclass
class TradeOutcome:
    """
    Stores actual result after trade is completed.
    """

    prediction_id: str

    entry_price: float

    exit_price: float

    quantity: int = 1

    holding_minutes: float = 0.0

    exit_reason: str = ""

    profit_points: float = 0.0

    pnl: float = 0.0

    success: bool = False

    timestamp: datetime = field(default_factory=datetime.now)


# ==========================================================
# Pattern Statistics
# ==========================================================

@dataclass
class PatternStatistics:

    pattern_id: str

    pattern_key: str

    description: str

    total_occurrences: int = 0

    wins: int = 0

    losses: int = 0

    average_profit: float = 0.0

    average_loss: float = 0.0

    win_rate: float = 0.0

    last_seen: str = ""


# ==========================================================
# Strategy Statistics
# ==========================================================

@dataclass
class StrategyStatistics:
    """
    Performance of a strategy combination.
    """

    strategy_name: str

    total_trades: int = 0

    wins: int = 0

    losses: int = 0

    win_rate: float = 0.0

    average_profit: float = 0.0

    average_loss: float = 0.0


# ==========================================================
# Learning Result
# ==========================================================

@dataclass
class LearningResult:
    """
    Returned by Learning Brain after analysis.
    """

    historical_matches: int = 0

    historical_win_rate: float = 0.0

    adjusted_confidence: float = 0.0

    recommendation: str = "HOLD"

    notes: List[str] = field(default_factory=list)


# ==========================================================
# Pattern Analysis
# ==========================================================

# ==========================================================
# Pattern Analysis
# ==========================================================

@dataclass
class PatternAnalysis:
    """
    Final result returned by Pattern Memory.
    """

    # Pattern Information
    pattern_key: str = ""

    fingerprint: str = ""

    # Historical Statistics
    historical_matches: int = 0

    wins: int = 0

    losses: int = 0

    win_rate: float = 0.0

    average_profit: float = 0.0

    average_loss: float = 0.0

    average_holding_minutes: float = 0.0

    # AI Recommendation
    confidence_bonus: float = 0.0
    pattern_confidence: float = 0.0

    recommendation: str = "HOLD"

    # Debug / Explainability
    matched_predictions: list[str] = field(default_factory=list)

    similarity_scores: list[float] = field(default_factory=list)

    notes: list[str] = field(default_factory=list)


from dataclasses import dataclass
from datetime import datetime


# ==========================================================
# Learned Pattern
# ==========================================================

@dataclass
class LearnedPattern:
    """
    Represents a learned historical trading pattern.
    """

    fingerprint: str

    matches: int = 0

    wins: int = 0

    losses: int = 0

    win_rate: float = 0.0

    average_profit: float = 0.0

    average_loss: float = 0.0

    confidence_bonus: float = 0.0

    recommendation: str = "HOLD"

    age_score: float = 100.0

    last_updated: datetime | None = None
# ==========================================================
# Market Features
# ==========================================================

@dataclass
class MarketFeatures:
    """
    Normalized market features used for learning.
    """

    symbol: str

    timeframe: str

    decision: str

    confidence: float

    price_action: str

    live_market: str

    options: str

    global_market: str

    trend: str

    atr_bucket: str

    vix_bucket: str

    support_distance: float

    resistance_distance: float

    market_session: str

    confidence_bucket: str

    brain_agreement: int

    extra: dict = field(default_factory=dict)

# ==========================================================
# Optimized Confidence
# ==========================================================

@dataclass
class OptimizedConfidence:
    """
    Final optimized confidence returned by
    Confidence Optimizer.
    """

    base_confidence: float

    final_confidence: float

    pattern_bonus: float = 0.0

    agreement_bonus: float = 0.0

    volatility_penalty: float = 0.0

    historical_bonus: float = 0.0

    risk_penalty: float = 0.0

    adjustments: list[str] = field(default_factory=list)

from dataclasses import dataclass, field

@dataclass
class StrategyRecommendation:
    """
    Final recommendation generated by the
    Strategy Learning engine.
    """

    recommendation: str

    confidence: float

    risk_multiplier: float

    position_multiplier: float

    stop_loss_multiplier: float

    take_profit_multiplier: float

    reasoning: list[str] = field(default_factory=list)

